package ba.unsa.etf.rpr.business;

import ba.unsa.etf.rpr.dao.DaoFactory;
import ba.unsa.etf.rpr.domain.Book;
import ba.unsa.etf.rpr.exceptions.LibraryException;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.TreeMap;

public class BookManager {
    public List<Book> getAll() throws LibraryException {
        return DaoFactory.bookDao().getAll();
    }
    public void viewAll() throws LibraryException {
        DaoFactory.bookDao().viewAll();
    }
    public List<Book> searchByAuthor(String author) throws LibraryException {
        return DaoFactory.bookDao().searchByAuthor(author);
    }
    public List<Book> searchByGenre(String genre) throws LibraryException {
        return DaoFactory.bookDao().searchByGenre(genre);
    }

    public List<Book> searchByTitle(String title) throws LibraryException {
        return DaoFactory.bookDao().searchByTitle(title);
    }

   /* public Book searchByTitleAndAuthor(String title, String author) throws LibraryException {
        return DaoFactory.bookDao().searchByTitleAndAuthor(title, author);
    }*/

    public boolean isAvailable(int id) throws LibraryException {
        return DaoFactory.bookDao().isAvailable(id);
    }
    public Book add(Book item) throws LibraryException {
        if(item.getId() != 0) throw new LibraryException("Can't add book with ID. ID is autogenerated");
        validateBook(item);
        return DaoFactory.bookDao().add(item);
    }

    public Book update(Book item) throws LibraryException {
        validateBook(item);
        return DaoFactory.bookDao().update(item);
    }

    public void delete(Book item) throws LibraryException {
        DaoFactory.bookDao().delete(item);
    }


   /* @Override
    public Book getById(int id) throws LibraryException {
        return DaoFactory.bookDao().getB
    }*/

    public Book searchById(int id) throws LibraryException {
        return DaoFactory.bookDao().searchById(id);
    }
    public List<Book> removeAll() throws LibraryException {
        return DaoFactory.bookDao().removeAll();
    }
    public void validateBook(Book item) throws LibraryException {
        if (!item.getYearOfPublication().matches("\\d*")) {
            throw new LibraryException("The year of publication can only contain numbers!");
        }
        if(Integer.parseInt(item.getYearOfPublication()) < 1 || Integer.parseInt(item.getYearOfPublication()) > LocalDate.now().getYear()) {
            throw new LibraryException("Year can't be negative or greater than current year!");
        }
        if(item.getTotalNumber() < 0 || item.getTotalNumber() > 100) {
            throw new LibraryException("Total number of books can't be negative or greater than 100!");
        }
        if(item.getAvailableNumber() < 0 || item.getAvailableNumber() > 100) {
            throw new LibraryException("Available number of books can't be negative or greater than 100!");
        }
        if(!item.getTitle().matches("^[\\S]+(\\s[\\S]+)*$")) {
            throw new LibraryException("Space can only be located between 2 sets of characters.");
        }
        if(item.getTitle().length() < 1 || item.getTitle().length() > 200) {
            throw new LibraryException("Title can't be empty of longer than 200 characters!");
        }
        if(!item.getAuthor().matches("^[\\S]+(\\s[\\S]+)*$")) {
            throw new LibraryException("Space can only be located between 2 sets of characters.");
        }
        if(item.getAuthor().length() < 1 || item.getAuthor().length() > 100) {
            throw new LibraryException("Authors name can't be empty of longer than 100 characters!");
        }
        if(!item.getGenre().matches("^[\\S]+(\\s[\\S]+)*$")) {
            throw new LibraryException("Space can only be located between 2 sets of characters.");
        }
        if(item.getGenre().length() < 3 || item.getGenre().length() > 50) {
            throw new LibraryException("Genre length must be between 3 and 50 characters!");
        }
        if(item.getAvailableNumber() > item.getTotalNumber()) {
            throw new LibraryException("The number of available books cannot be greater than the total number of books!");
        }
    }
}
